language: node_js
node_js:
  - "6"
branches:
  only:
    - master

addons:
  firefox: latest
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules
    - typings


berfore_script:
  - npm install -g firebase-tools
  - npm install -g webpack
  - npm install

script:
  - npm run build

after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}


notifications:
  webhooks:
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
